### ISSUE TITLE
不支持枚举映射语法

### ISSUE THREAD

**Issue by EmyiaEllen** [ClearPlume/jimmer-dto#1]
dto 文件中使用 枚举映射 语法会报错

![image](https://github.com/ClearPlume/jimmer-dto/assets/82955455/dee0b882-b8a1-4f2b-99f0-cd3ef951a9fa)

取消使用枚举映射后正常

![image](https://github.com/ClearPlume/jimmer-dto/assets/82955455/e02327ca-2afc-4827-aa5a-55151cacba9c)

IDEA报错提示：
```text
应为 <explicit prop>, <prop body>, DTOTokenType.!, DTOTokenType.(, DTOTokenType.,, DTOTokenType.:, DTOTokenType.;, DTOTokenType.?, DTOTokenType.as 或 DTOTokenType.}，得到 '->'
```

---

系统环境: IDEA 2023.2, Jimmer DTO 插件 0.0.6

**Comment by ClearPlume** [comment]
0.0.7已支持
