### ISSUE TITLE
[Feature Request] Add a new code prompt indicating that users should fill in the attributes of the associated object when using it.

### ISSUE THREAD

**Issue by WackyGem** [ClearPlume/jimmer-dto#16]
For example, in the following scenario:
```
BookStoreView {
    name,
    books            // Unexpected code
    books {
        #allScalars  // Compilable code
    }
}
```

**Comment by ClearPlume** [comment]
There should be no error messages for child-body related to recursive prop

![recursive-prop-child-body-prompt](https://github.com/user-attachments/assets/0469eeff-0ed1-44c2-8207-a5bf17f3f462)

**Comment by ClearPlume** [comment]
It hasn't been fixed yet
