### ISSUE TITLE
`0.0.7`版本，实体中继承自`MappedSuperClass`中的属性在dto中使用时会标红

### ISSUE THREAD

**Issue by JackyLeeCS** [ClearPlume/jimmer-dto#2]
<img width="215" alt="image" src="https://github.com/ClearPlume/jimmer-dto/assets/8992971/7c0dac07-b5cf-4275-a3f7-05ceae36b59f">
<img width="368" alt="image" src="https://github.com/ClearPlume/jimmer-dto/assets/8992971/5d22b40c-8311-42ed-8de1-0f527f29f918">

**Comment by ClearPlume** [comment]
0.0.7.2已修复

**Comment by JackyLeeCS** [comment]
`createdBy`内部的属性还是会标红
<img width="351" alt="image" src="https://github.com/ClearPlume/jimmer-dto/assets/8992971/167a6e38-7c4e-4538-a8df-6330dc847ca6">

**Comment by ClearPlume** [comment]
`createdBy`是继承自MappedSuperClass的关联属性？明白了，我再看看

**Comment by ClearPlume** [comment]
0.0.7.5已修复
