### ISSUE TITLE
package 颜色不正常

### ISSUE THREAD

**Issue by mtpkiss** [ClearPlume/jimmer-dto#5]
dto文件导出颜色显示不正常,类似下面的代码
```
export com.yourcompany.yourproject.Book
    -> package com.yourcompany.yourproject.mydto
```
颜色显示如下图所示,出现了不该出现的红色波浪线

![image](https://github.com/ClearPlume/jimmer-dto/assets/3182367/8c1278ef-f9a4-490b-b917-f41467d43c97)

idea 版本 `2023.3.4`

plugin 版本 `0.0.7.11`

**Comment by ClearPlume** [comment]
0.0.7.12修复
