### ISSUE TITLE
[Bug] 单 dto 文件模块中没有 export 语句时插件提示错误

### ISSUE THREAD

**Issue by ArgonarioD** [ClearPlume/jimmer-dto#6]
jimmer dto 中，单 dto 文件模块应该是不需要 export 语句的。但插件对于没有 export 语句的单 dto 文件模块进行了错误的错误提示，并且错误提示中没有任何错误信息。
<img width="507" alt="f04dea88ed8cf2cd7c2420e678759e6f" src="https://github.com/ClearPlume/jimmer-dto/assets/15799382/c5413642-411b-412a-8304-f8eacfe28732">

**Comment by ClearPlume** [comment]
0.0.7.16下测试未发现问题，0.0.7.17也没有问题
