### ISSUE TITLE
在flat函数里写了双引号不能删除双引号，删除键失效

### ISSUE THREAD

**Issue by Atomzzm** [ClearPlume/jimmer-dto#9]
<img width="260" alt="image" src="https://github.com/ClearPlume/jimmer-dto/assets/162692650/4f6b8995-1ad0-4d1e-b0de-643bd5ced7f2">
在flat函数里写了双引号不能删除双引号，删除键失效

**Comment by ClearPlume** [comment]
0.0.7.18已修复

![图片](https://github.com/ClearPlume/jimmer-dto/assets/18047536/a657220e-071e-4212-9414-4e307d6a923f)
